security:
    encoders:
        EsportBundle\Entity\Player:
            algorithm: md5
            encode-as-base64: true
            iterations: 10
    role_hierarchy:
            ROLE_ADMIN: [ROLE_CAPITAINE]
            ROLE_CAPITAINE: [ROLE_USER]
    providers:
        userDB:
            entity: { class: EsportBundle\Entity\Player, property: gamertag}
    firewalls:
        main:
            pattern: /.*
            provider: userDB
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
                default_target_path: /dashboard
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiPassphrase
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true

