<?php

namespace EsportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayersGamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayersGamesRepository extends EntityRepository
{
}
